# -*- coding: utf-8 -*-
"""diff_img_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OhePVsOTHcpy3Ei1UGnesH2RJrQNoGCu
"""

import cv2
import numpy as np
import os
import math
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

images_dir = "/content/drive/MyDrive/ПОПЫТКА 2"



images_names = os.listdir(images_dir)
img_count = len(images_names)
difference_matrix = np.zeros((img_count,img_count))
similarity_matrix = np.zeros((img_count,img_count))
names = []
for i in range(img_count):
    names.append(images_names[i])
    current_image = cv2.imread(os.path.join(images_dir,images_names[i]))
    gray_current = cv2.cvtColor(current_image, cv2.COLOR_BGR2GRAY)
    for j in range(img_count):
        
        target_img = cv2.imread(os.path.join(images_dir,images_names[j]))
        target_img = cv2.resize(target_img,(current_image.shape[1],current_image.shape[0]))
        gray_target = cv2.cvtColor(target_img, cv2.COLOR_BGR2GRAY)
        dif = (np.sum(current_image!=target_img))
        count_px = current_image.shape[0] * current_image.shape[1]*3
        #на сколько похожи 
        elem  = round((1 - (dif / count_px )),5)
        similarity_matrix[i][j] = elem * 100

        #на сколько отличаются 
        elem  = round((dif / count_px ),5)
        difference_matrix[i][j] = elem * 100

print("Матрица различий")
print(difference_matrix)

print()
print("Матрица схожести")
print(similarity_matrix)

def show_matrix(matrix):
  fig, ax = plt.subplots()
  ax.matshow(matrix, cmap=plt.cm.Dark2)
  for i in range(matrix.shape[0]):
      for j in range(matrix.shape[1]):
          c = round(matrix[j,i],4)
          ax.text(i, j, str(c), va='center', ha='center',color='white')

print("Матрица схожести")
show_matrix(similarity_matrix)

print("Матрица различий")
show_matrix(difference_matrix)

import pandas as pd
df = pd.DataFrame(similarity_matrix)
df.to_csv("схожесть.csv",index=False)
df = pd.DataFrame(difference_matrix)
df.to_csv("различие.csv",index=False)

df

import pandas as pd
df = pd.DataFrame(similarity_matrix)
df.to_csv("схожесть.csv",index=False)
df = pd.DataFrame(difference_matrix)
df.to_csv("различие.csv",index=False)

names

